### PR TITLE
Add open-source licenses

### PR DESCRIPTION
**Pull request by jcp19**
As discussed in the last Gobra meeting, our standard library stubs contain code from the original Go code, or are otherwise heavily inspired on it. As such, they must comply with the [Go license](https://golang.org/LICENSE). Besides, the license file must be redistributed with the source-code and its contents must be reproduced in distributions in binary form.

This PR adds the copyright notice to the affected files and introduces a new `docs/licenses` directory that contains copyright notices that must be included in source-code redistributions.

### CODE REVIEW

**Comment by ArquintL** [comment]
Could you please adapt the config file for the license header checker as well?

**Comment by ArquintL** [comment]
@jcp19 I think you have to remove line 8 in `.github/license-check/config.json` and add that include path together with the path to the corresponding license header file as an additional item in the config

**Comment by jcp19** [comment]
Yes, I just noticed that. Thank you for such a quick review!

**Review by Felalolf — APPROVED** [review]

**Review by ArquintL — APPROVED** [review]
Looks good to me

**Pull request merged**
