### PR TITLE
Enable bors

### PR DESCRIPTION
**Pull request by vakaras**

### CODE REVIEW

**Comment by vakaras** [comment]
bors ping

**Comment by vakaras** [comment]
@ArquintL If you like it, type `bors r+`.

**Comment by ArquintL** [comment]
Ah it does not automatically merge all PRs. We have to type `bors r+` for every PR we would like to have merged like that, right?

**Comment by vakaras** [comment]
> Ah it does not automatically merge all PRs. We have to type `bors r+` for every PR we would like to have merged like that, right?

Yes. `r+` stands for “I have reviewed this PR and I am happy with it”.

**Review by ArquintL — APPROVED** [review]

**Comment by vakaras** [comment]
> Timed out.

@ArquintL The reason for this is that `check-license-headers` is not running on the `staging` branch.

**Comment by vakaras** [comment]
> This PR was included in a batch that successfully built, but then failed to merge into master. It will not be retried.
> 
> Additional information:
> 
> ```json
> {"message":"You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.","documentation_url":"https://docs.github.com/articles/about-protected-branches"}
> ```

@ArquintL From the [documentation](https://bors.tech/documentation/getting-started/):

> You can check this on GitHub in your repository’s Settings tab, in the Branches section. The “master” branch can be protected, and since bors will usually be the only thing that commits directly to master, you can set it to require the “bors” Commit Status to push to master. Do not set the staging/trying branches to protected.

**Comment by ArquintL** [comment]
bors has now been added to the list of people authorized to push to `master`

**Pull request merged**
