### PR TITLE
Fix #734

### LINKED ISSUE #734: Paranthesis omitted in toString of Internal AST
For instance, the statement `assert 0 == 5 - (2+3)` is printed as "assert 0 == 5 - 2 + 3".

### PR DESCRIPTION
**Pull request by Felalolf**
This PR fixes issue 734 with the simplest solution by always adding parantheses around binary expressions.
This solution results in many unnecessary parantheses. Please tell me if you think that this is not ok. In that case, the printer would require some state tracking whether a child expression may omit parantheses.

### CODE REVIEW

**Comment by Felalolf** [comment]
The failing tests are the printer tests. I will change them after we agree on the parantheses.

**Review by jcp19 — APPROVED** [review]
This is alright, but maybe we can be a bit more parsimonious with the parentheses. Maybe, we could just emit them for a few binary expressions like Subtraction and Division, and keep it as is for addition and the other associative operators

**Comment by Felalolf** [comment]
I do not think this solves the problem, e.g. `a + (b * c)` and  `(a + b) * c` are also different. On first glance, it seems that we can get rid of the paranthesis for multiplication and the equality operators.

**Comment by jcp19** [comment]
> I do not think this solves the problem, e.g. `a + (b * c)` and `(a + b) * c` are also different. On first glance, it seems that we can get rid of the paranthesis for multiplication and the equality operators.

Fine by me

**Comment by jcp19** [comment]
(Closed by mistake, reopened again)

You are right, my suggestion is bad. I think that we still need parens for equality: `(a == b) == c` and `a == (b == c)` would both be pretty-printed as `a == b == c` otherwise

**Comment by jcp19** [comment]
Let's proceed with your original suggestion then.

**Review by jcp19 — APPROVED** [review]

**Pull request merged**
