### PR TITLE
Optimizes Channel Encoding and Catches Known Z3 Bug

### PR DESCRIPTION
**Pull request by ArquintL**
In addition, this PR improves the Dockerfile such that a specified Z3 version instead of the latest Z3 version is used while building the container used for CI.

This PR will be squash commited to shrink all commits of this PR into one.

### CODE REVIEW

**Comment by Felalolf** [comment]
Do we want to now always check both z3 versions?

**Comment by ArquintL** [comment]
> Do we want to now always check both z3 versions?

I've just removed the corresponding instructions from the CI script but I can reintroduce them

**Review by Felalolf — APPROVED** [review]
Did you make sure that it actually catches the bug?

**Comment by ArquintL** [comment]
> Did you make sure that it actually catches the bug?

Yes but manually causing a NPE in the Silicon file. The output looks as follows for a test case (the test case still counts as failed):
```
[info] - regressions/examples/impl_errors/Tree.gobra [Gobra] *** FAILED ***
[info]   viper.gobra.util.Violation$KnownZ3BugException: Encountered a known Z3 bug. Please, execute the file again.
[info]   at viper.gobra.Gobra$$anonfun$verifyAst$2.applyOrElse(Gobra.scala:100)
[info]   at viper.gobra.Gobra$$anonfun$verifyAst$2.applyOrElse(Gobra.scala:97)
[info]   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:454)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
```

**Review by jcp19 — APPROVED** [review]

**Pull request merged**
