### PR TITLE
Havoc

### PR DESCRIPTION
**Pull request by viper-admin**
>  **Pull request** :twisted_rightwards_arrows: created by **@arquintl** on 2019-12-13 17:26
> Last updated on 2019-12-16 10:13
> Original Bitbucket pull request id: 7
>
> Participants:
>
> * **@Felalolf** (reviewer)
>
> Source: https://github.com/viperproject/gobra/commit/a11c86ec42170255fe2a3441a9aeecb0fd29e182 on branch `havoc-var`
> Destination: https://github.com/viperproject/gobra/commit/729e2ba249fdc679653090c7b1569e95ce721ed0 on branch `master`
>
> State: **`OPEN`**

In case this PR is not merged, commit [a11c86e](https://github.com/viperproject/gobra/commit/<https://github.com/viperproject/gobra/commit/a11c86ec42170255fe2a3441a9aeecb0fd29e182>) should be cherry-picked

‌

### CODE REVIEW

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 09:57
>
> **Location:** line 182 of `src/main/scala/viper/gobra/ast/internal/Program.scala`

Currently, havoc is a normal statement. But it will have to be a ghost statement eventually. 

I have just noticed that the same holds for all other proof statements so far \(exhale, inhale, fold, unfold\). I will create a separate issue for that.

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 09:58
>
> **Location:** line 288 of `src/main/scala/viper/gobra/frontend/Parser.scala`

Shouldn’t this be “havoc”?

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:00
>
> **Location:** line 25 of `src/main/scala/viper/gobra/frontend/info/implementation/typing/ghost/GhostStmtTyping.scala`

This seems too weak to me. What happens, when you try to havoc a non-havocable expression, e.g. “havoc foo\(x\)“?

Since you permit arbitrary expressions for the parsing of havoc, I would expect a check that determines if the expression is actually havocable.

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:04
>
> **Location:** line 439 of `src/main/scala/viper/gobra/translator/implementations/translator/LocationsImpl.scala`

The encoding annotations is missing.

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:07
>
> **Location:** line 35 of `src/main/scala/viper/gobra/translator/implementations/translator/StatementsImpl.scala`

Are those two functions still used?

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:08
>
> **Location:** line 10 of `src/test/resources/regressions/features/havoc/havoc-field-3.go`

This is the same test as havoc-field-2.go

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:09
>
> **Location:** line 10 of `src/test/resources/regressions/features/havoc/havoc-loc-1.go`

This is the same test as havoc-field-1.go.

Youd could add a test where \*p is havoced.

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:12
>
> **Location:** line 15 of `src/test/resources/regressions/features/havoc/havoc-loc-2.go`

I would try to keep one error per test. In the uture we might use carbon as a backend, and then we would get multiple errors \(making this case fail\).

**Comment by viper-admin** [comment]
> **@Felalolf** commented on 2019-12-16 10:12
>
> **Location:** line 25 of `src/test/resources/regressions/features/havoc/havoc-loc-3.go`

I would try to keep one error per test. In the uture we might use carbon as a backend, and then we would get multiple errors \(making this case fail\).

**Comment by jcp19** [comment]
@Felalolf @ArquintL can we close this PR?

**Comment by ArquintL** [comment]
Unless we really want to have `havoc` in the language, I'm also in favor of closing it. Was a nice exercise at the very beginning of my PhD

**Pull request closed without merging**
